import React, { useState, useCallback, useEffect } from 'react';
import JSZip from 'jszip';
import { Settings, Play, Download, Trash2, AlertCircle, Film, Sparkles } from 'lucide-react';
import { extractFramesFromVideo } from './utils/videoProcessor';
import { generateVideoPrompt } from './utils/ai';
import { FrameData, AppState } from './types';
import { Uploader } from './components/Uploader';
import { Button } from './components/Button';
import { ResultGrid } from './components/ResultGrid';

export default function App() {
  // State
  const [file, setFile] = useState<File | null>(null);
  const [interval, setInterval] = useState<number>(3);
  const [frames, setFrames] = useState<FrameData[]>([]);
  const [appState, setAppState] = useState<AppState>(AppState.IDLE);
  const [progress, setProgress] = useState<number>(0);
  const [log, setLog] = useState<string>("");
  const [error, setError] = useState<string | null>(null);

  // Cleanup object URLs on unmount or reset
  useEffect(() => {
    return () => {
      frames.forEach(f => URL.revokeObjectURL(f.url));
    };
  }, [frames]);

  const handleReset = () => {
    if (confirm("Apakah Anda yakin ingin menghapus semua hasil dan mulai ulang?")) {
      frames.forEach(f => URL.revokeObjectURL(f.url));
      setFrames([]);
      setFile(null);
      setAppState(AppState.IDLE);
      setProgress(0);
      setLog("");
      setError(null);
    }
  };

  const handleProcess = useCallback(async () => {
    if (!file) return;

    setAppState(AppState.PROCESSING);
    setError(null);
    setProgress(0);
    setFrames([]);

    try {
      const resultFrames = await extractFramesFromVideo(
        file, 
        interval, 
        (current, total, message) => {
          const percentage = total > 0 ? Math.round((current / total) * 100) : 0;
          setProgress(percentage);
          setLog(message);
        }
      );
      setFrames(resultFrames);
      setAppState(AppState.COMPLETED);
    } catch (err: any) {
      setError(err.message || "Terjadi kesalahan saat memproses video.");
      setAppState(AppState.ERROR);
    }
  }, [file, interval]);

  const handleGenerateAiPrompts = async () => {
    if (frames.length === 0) return;

    const previousState = appState;
    setAppState(AppState.ANALYZING);
    setLog("Mempersiapkan analisis AI...");
    setProgress(0);

    const newFrames = [...frames];
    let processedCount = 0;

    // Process sequentially to be gentle on rate limits
    for (let i = 0; i < newFrames.length; i++) {
      if (newFrames[i].aiPrompt) {
        processedCount++;
        continue;
      }

      setLog(`Menganalisis frame ${i + 1}/${newFrames.length} dengan Gemini AI...`);
      
      try {
        const prompt = await generateVideoPrompt(newFrames[i].blob);
        newFrames[i] = { ...newFrames[i], aiPrompt: prompt };
        // Update state periodically so UI refreshes
        setFrames([...newFrames]);
      } catch (e) {
        console.error("Error creating prompt for frame " + i, e);
      }

      processedCount++;
      setProgress(Math.round((processedCount / newFrames.length) * 100));
    }

    setLog("Analisis AI Selesai.");
    setAppState(previousState);
  };

  const handleDownloadZip = async () => {
    if (frames.length === 0) return;
    
    const zip = new JSZip();
    const folder = zip.folder("frames");
    let promptsText = "Video Extraction Prompts\nGenerated by Gemini AI\n\n";
    
    if (folder) {
      frames.forEach(frame => {
        folder.file(frame.fileName, frame.blob);
        if (frame.aiPrompt) {
          promptsText += `--- ${frame.fileName} ---\n${frame.aiPrompt}\n\n`;
        }
      });
      
      // Include prompts file if any exist
      if (frames.some(f => f.aiPrompt)) {
        zip.file("prompts.txt", promptsText);
      }
      
      const content = await zip.generateAsync({ type: "blob" });
      const url = URL.createObjectURL(content);
      const a = document.createElement("a");
      a.href = url;
      a.download = `frames_with_prompts_${file?.name || 'video'}.zip`;
      a.click();
      URL.revokeObjectURL(url);
    }
  };

  return (
    <div className="min-h-screen bg-slate-50 py-8 px-4 sm:px-6 lg:px-8">
      <div className="max-w-6xl mx-auto space-y-8">
        
        {/* Header */}
        <div className="text-center space-y-3">
          <div className="inline-flex items-center justify-center p-3 bg-gradient-to-br from-blue-600 to-purple-600 rounded-2xl shadow-lg mb-2">
            <Film className="w-8 h-8 text-white" />
          </div>
          <h1 className="text-3xl font-bold text-slate-900">Ekstraktor Frame Video + AI</h1>
          <p className="text-slate-600 max-w-2xl mx-auto">
            Ekstrak frame dari video dan gunakan <span className="text-purple-600 font-semibold">Gemini AI</span> untuk 
            membuat prompt video generasi secara otomatis.
          </p>
        </div>

        {/* Main Card */}
        <div className="bg-white rounded-2xl shadow-sm border border-slate-200 overflow-hidden">
          <div className="p-6 md:p-8 space-y-8">
            
            {/* 1. Upload Section */}
            <div className="space-y-4">
              <div className="flex items-center justify-between">
                <h2 className="text-lg font-semibold text-slate-800 flex items-center gap-2">
                  <span className="flex items-center justify-center w-6 h-6 rounded-full bg-blue-100 text-blue-600 text-sm">1</span>
                  Pilih Video
                </h2>
                {(appState === AppState.COMPLETED || appState === AppState.ANALYZING) && (
                  <Button variant="ghost" size="sm" onClick={handleReset} className="text-red-500 hover:text-red-600 hover:bg-red-50">
                    <Trash2 className="w-4 h-4 mr-1" /> Mulai Ulang
                  </Button>
                )}
              </div>
              <Uploader 
                onFileSelect={setFile} 
                selectedFile={file} 
                disabled={appState === AppState.PROCESSING || appState === AppState.ANALYZING} 
              />
            </div>

            {/* 2. Configuration */}
            <div className="space-y-4">
               <h2 className="text-lg font-semibold text-slate-800 flex items-center gap-2">
                <span className="flex items-center justify-center w-6 h-6 rounded-full bg-blue-100 text-blue-600 text-sm">2</span>
                Konfigurasi
              </h2>
              <div className="flex flex-col sm:flex-row items-start sm:items-end gap-4 p-4 bg-slate-50 rounded-lg border border-slate-100">
                <div className="flex-1 w-full">
                  <label className="block text-sm font-medium text-slate-700 mb-1">
                    Interval Ekstraksi (Detik)
                  </label>
                  <div className="relative">
                    <Settings className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" />
                    <input
                      type="number"
                      min="0.5"
                      step="0.5"
                      value={interval}
                      onChange={(e) => setInterval(Math.max(0.1, parseFloat(e.target.value)))}
                      disabled={appState !== AppState.IDLE && appState !== AppState.ERROR}
                      className="w-full pl-10 pr-4 py-2 border border-slate-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 disabled:bg-slate-100 disabled:text-slate-500 transition-all"
                    />
                  </div>
                  <p className="text-xs text-slate-500 mt-1">
                    Ambil 1 gambar setiap <strong>{interval}</strong> detik.
                  </p>
                </div>
                
                <div className="flex-shrink-0 w-full sm:w-auto">
                  {appState === AppState.IDLE || appState === AppState.ERROR ? (
                    <Button 
                      onClick={handleProcess} 
                      disabled={!file} 
                      className="w-full sm:w-auto"
                      icon={<Play size={18} fill="currentColor" />}
                    >
                      Mulai Proses
                    </Button>
                  ) : appState === AppState.PROCESSING || appState === AppState.ANALYZING ? (
                     <Button 
                      disabled 
                      isLoading 
                      className="w-full sm:w-auto"
                    >
                      {appState === AppState.PROCESSING ? 'Memproses Video...' : 'Menganalisis AI...'}
                    </Button>
                  ) : (
                    <div className="flex flex-col sm:flex-row gap-2">
                       <Button 
                        variant="primary"
                        onClick={handleDownloadZip}
                        className="w-full sm:w-auto bg-green-600 hover:bg-green-700 focus:ring-green-500"
                        icon={<Download size={18} />}
                      >
                        Unduh ZIP
                      </Button>
                    </div>
                  )}
                </div>
              </div>
            </div>

            {/* Error Message */}
            {error && (
              <div className="p-4 bg-red-50 border border-red-200 rounded-lg text-red-700 flex items-start gap-3">
                <AlertCircle className="w-5 h-5 flex-shrink-0 mt-0.5" />
                <div>
                  <p className="font-medium">Terjadi Kesalahan</p>
                  <p className="text-sm opacity-90">{error}</p>
                </div>
              </div>
            )}

            {/* Progress Bar */}
            {(appState === AppState.PROCESSING || appState === AppState.ANALYZING) && (
              <div className="space-y-2 animate-in fade-in slide-in-from-top-4 duration-300">
                <div className="flex justify-between text-sm text-slate-600">
                  <span className="flex items-center gap-2">
                    {appState === AppState.ANALYZING && <Sparkles className="w-4 h-4 text-purple-500 animate-pulse" />}
                    {log}
                  </span>
                  <span className="font-medium">{progress}%</span>
                </div>
                <div className="w-full h-2 bg-slate-100 rounded-full overflow-hidden">
                  <div 
                    className={`h-full transition-all duration-300 ease-out ${appState === AppState.ANALYZING ? 'bg-purple-600' : 'bg-blue-600'}`}
                    style={{ width: `${progress}%` }}
                  />
                </div>
              </div>
            )}

            {/* Results */}
            {frames.length > 0 && (
              <div className="animate-in fade-in slide-in-from-bottom-8 duration-500 border-t border-slate-100 pt-8">
                <ResultGrid 
                  frames={frames} 
                  onGeneratePrompts={handleGenerateAiPrompts}
                  isGenerating={appState === AppState.ANALYZING}
                />
              </div>
            )}

          </div>
        </div>
      </div>
    </div>
  );
}